<a href="https://colab.research.google.com/github/awfajri/artificial-intelligence/blob/main/Praktikum_Pertemuan_4_Auf_Fajri_Ramadhani.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tugas Pertemuan 4 - Auf Fajri Ramadhani

Kelas : 4F

NPM : 2410631170059



---

#**Soal**

1.   Jelaskan setiap tahapan pada kode diatas!
2.   Apa output yang didapat dari kode diatas? jelaskan!

#**Jawab**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv("employee.csv")
dataset

     ID    Name  Age  Years of Service  Salary
0  NO01     Ani   35                 3    2940
1  NO02    Budi   26                 2    3440
2  NO03    Risa   30                 6    3000
3  NO04    Soni   41                12    3800
4  NO05    Huda   39                13    6400
5  NO06    Rani   34                 1    2200
6  NO07     Ria   37                 4    4160
7  NO08   Ridho   49                17    6000
8  NO09   Rusdi   37                 5    5000
9  NO10  Burhan   36                14    5020

In [ ]:
#get the age attribute's value
dage=np.array(dataset)
dage=dage[:,[0,2]]
print("index 0 = ID, index 1 = age")
pd.DataFrame(dage)

index 0 = ID, index 1 = age

      0   1
0  NO01  35
1  NO02  26
2  NO03  30
3  NO04  41
4  NO05  39
5  NO06  34
6  NO07  37
7  NO08  49
8  NO09  37
9  NO10  36

In [ ]:
age01=np.sum(dage[0:1,1],axis=0)
age02=np.sum(dage[1:2,1],axis=0)

print("age 01:", age01)
print("age 02:", age02)

In [ ]:
age01=np.sum(dage[0:1,1],axis=0)
age02=np.sum(dage[1:2,1],axis=0)
age03=np.sum(dage[2:3,1],axis=0)
age04=np.sum(dage[3:4,1],axis=0)
age05=np.sum(dage[4:5,1],axis=0)
age06=np.sum(dage[5:6,1],axis=0)
age07=np.sum(dage[6:7,1],axis=0)
age08=np.sum(dage[7:8,1],axis=0)
age09=np.sum(dage[8:9,1],axis=0)
age10=np.sum(dage[9:10,1],axis=0)

print("age 01:", age01)
print("age 02:", age02)
print("age 03:", age03)
print("age 04:", age04)
print("age 05:", age05)
print("age 06:", age06)
print("age 07:", age07)
print("age 08:", age08)
print("age 09:", age09)
print("age 10:", age10)

age 01: 35
age 02: 26
age 03: 30
age 04: 41
age 05: 39
age 06: 34
age 07: 37
age 08: 49
age 09: 37
age 10: 36

In [ ]:
dyos=np.array(dataset)
dyos=dyos[:,[0,3]]
print("index 0 = ID, index 1 = year of service")
pd.DataFrame(dyos)

index 0 = ID, index 1 = year of service

      0   1
0  NO01   3
1  NO02   2
2  NO03   6
3  NO04  12
4  NO05  13
5  NO06   1
6  NO07   4
7  NO08  17
8  NO09   5
9  NO10  14

In [ ]:
dsalary=np.array(dataset)
dsalary=dsalary[:,[0,4]]
print("index 0 = ID, index 1 = salary")
pd.DataFrame(dsalary)

index 0 = ID, index 1 = salary

      0     1
0  NO01  2940
1  NO02  3440
2  NO03  3000
3  NO04  3800
4  NO05  6400
5  NO06  2200
6  NO07  4160
7  NO08  6000
8  NO09  5000
9  NO10  5020

In [ ]:
salary01=np.sum(dsalary[0:1,1],axis=0)
salary02=np.sum(dsalary[1:2,1],axis=0)
salary03=np.sum(dsalary[2:3,1],axis=0)
salary04=np.sum(dsalary[3:4,1],axis=0)
salary05=np.sum(dsalary[4:5,1],axis=0)
salary06=np.sum(dsalary[5:6,1],axis=0)
salary07=np.sum(dsalary[6:7,1],axis=0)
salary08=np.sum(dsalary[7:8,1],axis=0)
salary09=np.sum(dsalary[8:9,1],axis=0)
salary10=np.sum(dsalary[9:10,1],axis=0)

print("salary 01:",salary01)
print("salary 02:",salary02)
print("salary 03:",salary03)
print("salary 04:",salary04)
print("salary 05:",salary05)
print("salary 06:",salary06)
print("salary 07:",salary07)
print("salary 08:",salary08)
print("salary 09:",salary09)
print("salary 10:",salary10)

salary 01: 2940
salary 02: 3440
salary 03: 3000
salary 04: 3800
salary 05: 6400
salary 06: 2200
salary 07: 4160
salary 08: 6000
salary 09: 5000
salary 10: 5020

In [ ]:
!pip install scikit-fuzzy

Collecting scikit-fuzzy
  Downloading scikit_fuzzy-0.5.0-py2.py3-none-any.whl.metadata (2.6 kB)
Downloading scikit_fuzzy-0.5.0-py2.py3-none-any.whl (920 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 920.8/920.8 kB 13.5 MB/s eta 0:00:00
Installing collected packages: scikit-fuzzy
Successfully installed scikit-fuzzy-0.5.0

In [ ]:
import skfuzzy as fuz
import matplotlib.pyplot as plt

In [ ]:
def OurRange (_lo,_hi,_step):
  ourr=np.arrange(_lo,_hi,_step)
  return ourr

def MembershipFunc1 (_rule, _our_range, _title, _label0, _label1, _label2):
  low=fuz.trim(_our_range, rule[0])
  middle=fuz.trim(_our_range, rule[1])
  high=fuz.trim(_our_range, rule[2])

  fig, ax=plt.subplots(nrows=1, figsize=(6,3))
  ax.plot(_our_range, low, 'b', linewidth=1.5, label=label0)
  ax.plot(_our_range, middle, 'g', linewidth=1.5, label=label1)
  ax.plot(_our_range, high, 'r', linewidth=1.5, label=label2)

  ax.set_title(_title)
  ax.legend()

  ax.spines['top'].set_visible(False)
  ax.spines['right'].set_visible(False)
  ax.get_xaxis().tick_bottom()
  ax.get_yaxis().tick_left()

  plt.tight_layout()
  plt.show()

  return low, middle, high